library(dplyr)
data <-read.csv("household_power_consumption.txt", sep = ";",stringsAsFactor=FALSE)
datadf <- tbl_dt(data)
rm(data)
filtereddata<-filter(datadf,Date == "1/2/2007" | Date == "2/2/2007")
filtereddata$Global_active_power <- as.numeric(filtereddata$Global_active_power)
filtereddata$Global_reactive_power <- as.numeric(filtereddata$Global_reactive_power)
hist(filtereddata$Global_active_power, main="Global Active Power",  xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
dev.copy(png,"plot1.png",width=480 , height = 480)
dev.off()
