library(dplyr)
data <-read.csv("household_power_consumption.txt", sep = ";",stringsAsFactor=FALSE)
datadf <- tbl_dt(data)
rm(data)
filtereddata<-filter(datadf,Date == "1/2/2007" | Date == "2/2/2007")
filtereddata$Global_active_power <- as.numeric(filtereddata$Global_active_power)
filtereddata$Global_reactive_power <- as.numeric(filtereddata$Global_reactive_power)
filtereddata$Date <- as.character(filtereddata$Date)
filtereddata$Time <- as.character(filtereddata$Time)
date <- vector()
time <- vector()
datetime <-vector()
date <- as.character(filtereddata$Date)
time <- as.character(filtereddata$Time)
datentime<-paste(date,time)
datetime <-strptime(datentime,"%d/%m/%Y %H:%M:%S")
yrange<-c(0,40)
plot(datetime,filtereddata$Sub_metering_1, type = "l", ylab = "Energy Sub Metering",xlab = " ",ylim=yrange)
par(new=T)
plot(datetime,filtereddata$Sub_metering_2, type = "l",col = "red",ylab = "Energy Sub Metering",xlab = " ",ylim=yrange)
par(new=T)
plot(datetime,filtereddata$Sub_metering_3, type = "l",col = "blue",ylab = "Energy Sub Metering",xlab = " ",ylim=yrange)
par(new=T)
legend("topright",pch ="-" ,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.5,pt.cex=1.2)
par(new=F)
dev.copy(png,"plot3.png",width=480 , height = 480)
dev.off()
